name 'kbrezina-role'
version '0.0.0'

dependency 'cloudsmith/apache2', '>=0.1.0'
dependency 'cloudsmith/newrelic', '>=0.1.0'
dependency 'cloudsmith/php5', '>=0.1.0'
dependency 'cloudsmith/twitterdemo', '>=0.1.0'
